### ISSUE TITLE
Dexterity default view raises verbose warnings on plone.autoform >= 1.7.0

### ISSUE THREAD

**Issue by datakurre** [plone/plone.autoform#21]
Dexterity IDublinCore-behavior fields ``title`` and ``description`` are omitted on display forms. Dexterity default view is based on a display form. Because fields are omitted, they cannot be ordered and move directive shouts out warnings. These KeyErrors did happend already on plone.autoform < 1.7.0, but they were hidden. Now they are visible and look scary.

```
2017-01-29 21:57:04 ERROR plone.autoform.base No field move possible for non-existing field named IDublinCore.title with target *
Traceback (most recent call last):
  File "./buildout.coredev/src/plone.autoform/plone/autoform/base.py", line 243, in _process_field_moves
    move(self, name, before=before, after=after, prefix=prefix)
  File "./plone.z3cform-0.9.0-py2.7.egg/plone/z3cform/fieldsets/utils.py", line 85, in move
    raise KeyError("Field %s not found" % field_name)
KeyError: 'Field IDublinCore.title not found'
```

**Comment by fgrcon** [comment]
@jensens  changed that to warnings in https://github.com/plone/plone.autoform/commit/cabd75ff2ba1185b953180b2694f8870e3a07832 .
But still I have situations where a huge number of such warnings messes up my logfiles:
```
2017-07-13 22:15:42 WARNING plone.autoform.base Field move to non-existing: field name: IDublinCore.description, rule: {'target': '*', 'dir': 'before'}
2017-07-13 22:15:42 WARNING plone.autoform.base Field move to non-existing: field name: IDublinCore.title, rule: {'target': '*', 'dir': 'before'}
```
 Not existing fields in a display view cannot be ordered - that's quite understandable. Would it not be ok, to just drop this warning or is there a better solution?

**Comment by jensens** [comment]
We may want a parameter for the move field which says 'allow failure'. For custom moves, at least while development, one wants warnings.

**Comment by MrTango** [comment]
maybe it's better to change it to debug log, like it is now it's more confusing than helping most of the time.
